### ISSUE TITLE
Command to create/list/get namespaces

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-db#5] opened 2018-02-20 16:37 UTC
As an admin user of the 0-db, you need to be able to create namespace.
A namespace is always protected by a password, and to be able to work in this namespace you need to first authenticate using the AUTH command.

List namespaces will just return all the namespaces available on the 0-db.
Get namespace will return some information about the namespace, like reserved storage sized, storage currently used...

**Comment by maxux** [comment] 2018-02-24 14:24
A lot of implementation are nearly done since https://github.com/zero-os/0-db/commit/eeaef8aff77bdcc7c847f404873418973dcab724

Missing:
- [ ] No admin account yet, everybody is admin
- [ ] No size restriction applied yet

Here are the commands implemented:
* `NSLIST` to lists namespaces
* `NSNEW [namespace]` to create a new namespace
* `NSINFO [namespace]` to gets information (and statistics) about a namespace
* `DBSIZE` to get the amount of keys on the current namespace
* `NSSET [namespace] property [value]` to set settings to the namespace
  * Property `password` to set the password, use `*` to clear it
  * Property `public` to set public access allowed or not
  * Property `maxsize` to set the maximum datasize allowed of the namespace

**Comment by maxux** [comment] 2018-02-26 09:27
Admin account is now set and namespace limitation is implemented.

**Comment by iwanbk** [comment] 2018-02-28 03:06
NSINFO result
```
# namespace\nname: ns\nentries: 6\npublic: yes\npassword: no\ndata_size_bytes: 24\ndata_size_mb: 0.00\ndata_limits_bytes: 0\nindex_size_bytes: 324\nindex_size_kb: 0.32\n
```
In regard to 0-stor, it still needs these fields:
-  ReadRequestPerHour  int64
-  WriteRequestPerHour int64

**Comment by iwanbk** [comment] 2018-02-28 03:12
```
NSNEW [namespace] to create a new namespace
```
Current behaviour is `NSNEW` returns error in case of the namespace already exists.
Is it the expected behaviour?

I propose for this command to have these return values:
- 1  : new namespace created
- 0 : namespace already exist
- error if failed

**Comment by zaibon** [comment] 2018-02-28 07:37
> In regard to 0-stor, it still needs these fields:

    ReadRequestPerHour int64
    WriteRequestPerHour int64


Is this required for minio ?
Cause otherwise, from the FTF grid perspective, we won't do request per hour, but TPS , transaction per second. This TPS metrics is also something that client will be able to pay for. 

> TPS = Transactions Per Sec as done by our ZDB (is independent of the size of the data stored during that transaction)

**Comment by iwanbk** [comment] 2018-02-28 07:53
> Is this required for minio ?

Nope

**Comment by maxux** [comment] 2018-03-06 02:24
Closing, since it's seems good. Any bug/crash/improvement should be in dedicated new issues.

**Closed as completed by maxux** 2018-03-06 02:24 UTC
