### ISSUE TITLE
0-db crash

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/0-db#20] opened 2018-03-01 15:16 UTC
```C
[+] redis: resp: 2 arguments
[+] command: request fd: 25, namespace: thedisk
[+] command: 'GET' [+1 args]
[+] command: get: lookup key: 0x0000e8675700
[+] command: get: entry found, flags: 0, data length: 4096
[+] command: get: data file: 0, data offset: 5728232
[+] redis: resp: 2 arguments
[+] command: request fd: 26, namespace: thedisk
[+] command: 'GET' [+1 args]
[+] command: get: lookup key: 0x0000e8685800
[+] command: get: entry found, flags: 0, data length: 4096
[+] command: get: data file: 0, data offset: 5794024
zdb(48373,0x7fff7c844000) malloc: *** error for object 0x141: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Happened when downloading 25MB of file, with 4096 bytes chunk.

Let me know if you need more info. (But it is likely that i can only give it tomorrow)

**Comment by iwanbk** [comment] 2018-03-01 23:13
more details.

I got it twice when running this simple test https://github.com/gigforks/minio/wiki/Running, but don't get it today anymore

I tried to simplify the case using this go script, also didn't catch the bug
```go
package main

import (
	"bytes"
	"crypto/rand"
	"log"

	"github.com/garyburd/redigo/redis"
)

const (
	addr      = "127.0.0.1:12345"
	namespace = "thedisk"
	blockSize = 4096
	numBlock  = 6000
	dummyKey  = "k"
)

func main() {
	// init conn
	conn, err := redis.Dial("tcp", addr)
	if err != nil {
		log.Fatalf("dial:%v", err)
	}
	_, err = conn.Do("SELECT", namespace)
	if err != nil {
		log.Fatalf("select:%v", err)
	}

	// set
	var (
		keys  [][]byte
		datas [][]byte
	)

	for i := 0; i < numBlock; i++ {
		data := make([]byte, blockSize)
		rand.Read(data)

		key, err := redis.Bytes(conn.Do("SET", dummyKey, data))
		if err != nil {
			log.Fatalf("set %v:%v", i, err)
		}
		keys = append(keys, key)
		datas = append(datas, data)
	}

	// get data back
	for i, key := range keys {
		data, err := redis.Bytes(conn.Do("GET", key))
		if err != nil {
			log.Fatalf("get %v:%v", i, err)
		}
		if !bytes.Equal(data, datas[i]) {
			log.Fatalf("diff : %v", i)
		}
	}
}

```

**Comment by maxux** [comment] 2018-06-20 08:21
Closing this since it was not reproduced for months now.

**Closed as completed by maxux** 2018-06-20 08:21 UTC
