### ISSUE TITLE
DEL feature for direct key mode

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/0-db#15] opened 2018-02-27 10:35 UTC
We need it as part of https://github.com/zero-os/0-stor/issues/516
cc @zaibon

**Comment by zaibon** [comment] 2018-02-27 11:24
~~This is by design not possible. In direct key mode. 0-db doesn't keep any index. Which mean you need the key to get the data back. So a DELETE opreation doesn't really make sense here~~
Forget this, we actually need to have this feature

**Comment by maxux** [comment] 2018-02-27 15:56
Since we use an index for the direct-key mode (even if it's not in memory), this is not relevant anymore.
Moreover, like this we could rebuild deleted-entry in index via the data-file only, and compactation will be able to remove entries to free space.

In addition, the process already re-read the header each time in direct mode, to ensure key validity (which is already performance reducer but needed), checking for a flag in this time is not a big cost.

I'll implement this :)

**Comment by maxux** [comment] 2018-02-27 20:35
Some points about this:
- Marking blocks as deleted will break the initial behaviors of « always-append », since we need to overwrite the header of the data to mark them as deleted. Actually this is not a big deal since the amount of data in the file itself won't change. Let assume this is okay.
- In direct-key mode, the offset is in the key itself, which means that we can't do any compaction of the data files (we can't remove data in the middle of the file, offset of the next data would changes).
  - We will be able to do compaction if latest data entries are flagged as removed, theses one can be removed without any side effect
  - We could use sparsefile feature to have holes in the files, but this could result in weird results if we don't treat them correctly.

**Comment by iwanbk** [comment] 2018-02-28 03:04
i've tested it and it worked.
By worked i mean : the deleted key is not exist anymore

**Comment by maxux** [comment] 2018-03-06 02:25
Closing, since it's seems good. Any bug/crash/improvement should be in dedicated new issues.

**Closed as completed by maxux** 2018-03-06 02:25 UTC
